version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  node-app:
    container_name: node-app
    build: .
    restart: always
    ports:
      - "8000:8000"

volumes:
  db:
